[package]
name = "aes-ndlr"
version = "0.0.3"
authors = ["Spuffynism"]
license = "MIT"
description = "An implementation of AES"
readme = "README.md"
repository = "https://github.com/Spuffynism/aes"

[dev-dependencies]
rand = "0.7"
